### ISSUE TITLE
História: Registro manual de receitas e despesas

### ISSUE THREAD

**Issue by carolkekas28** [Lima-Almeida/PlataformaFin#11]
Referência ao épico: #10 

**Como:** Usuário

**Eu gostaria de:** inserir manualmente despesas e receitas no aplicativo

**De forma que:** eu possa controlar todas as transações que não estão automatizadas

#### Critérios de aceitação

- O usuário deve conseguir inserir o valor, a data, e a descrição das transações.

- O sistema deve permitir a inclusão de despesas e receitas em categorias predefinidas.

**Comment by brenofranca83** [comment]
Também, duas operações em uma história. Despesa é uma coisa, receita é outra. Elas tem implicações diferentes no sistema. Até dá pra pensar em registrar "transações"... o que não tornaria essa história errada, mas a interação vai sempre demandar um "passo" a mais para determinar como uma entrada se é receita ou despesa.
