### ISSUE TITLE
História: Categorias personalizadas para despesas

### ISSUE THREAD

**Issue by carolkekas28** [Lima-Almeida/PlataformaFin#12]
Referência ao épico: #10 

**Como:** Usuário

**Eu gostaria de:** categorizar minhas despesas em categorias personalizadas

**De forma que:** eu possa visualizar em quais áreas estou gastando mais

#### Critérios de aceitação

- O sistema deve permitir ao usuário criar, editar e excluir categorias de despesas.

- O sistema deve permitir visualizar despesas por categoria em relatórios e gráficos.

**Comment by brenofranca83** [comment]
Claramente um caso de uma história que deveria ser quebrada. O primeiro critério indica 3 operações distintas!
