### ISSUE TITLE
História: Definir limites de gastos por categoria

### ISSUE THREAD

**Issue by carolkekas28** [Lima-Almeida/PlataformaFin#17]
Referência ao épico: #16 

**Como:** Usuário

**Eu gostaria de:** definir limites de gastos para cada categoria

**De forma que:** eu possa controlar meus gastos e evitar ultrapassar meu orçamento

#### Critérios de aceitação

- O sistema deve permitir definir um limite de gastos para cada categoria.

- O sistema deve notificar o usuário quando 80% e 100% do limite forem atingidos.

**Comment by satohoshi** [comment]
está em fase de desenvolvimento, precisa de pequenos ajustes e automatizar os testes
